name: Publish to NPM
run-name: 'Create Release Notes and Publish'

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,chore
          config_file: .github/tag-changelog-config.cjs

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.changelog.outputs.changes }}

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.15.0
          cache: 'npm'

      - name: Set Git Config
        run: |
          git config --local user.email "DL-HeadlessTech@thehutgroup.com"
          git config --local user.name "THG Altitude [bot]"

      - name: Setup npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install and Build
        run: |
          cd standalone-components-css
          npm install
          npm ci
          npm run build

      - name: Publish to npm
        run: |
          cd standalone-components-css
          npm version ${GITHUB_REF_NAME} --no-git-tag-version
          npm publish --access public
